package com.OxGames.Pluvia.ui.enums

enum class DialogType {
    SUPPORT,
    SYNC_CONFLICT,
    SYNC_FAIL,
    MULTIPLE_PENDING_OPERATIONS,
    PENDING_OPERATION_NONE,
    PENDING_UPLOAD,
    PENDING_UPLOAD_IN_PROGRESS,
    APP_SESSION_ACTIVE,
    APP_SESSION_SUSPENDED,

    INSTALL_APP,
    NOT_ENOUGH_SPACE,
    CANCEL_APP_DOWNLOAD,
    DELETE_APP,

    NONE,
}
