name: Bug report
description: File a bug report
title: "[Bug]: "
labels: bug
assignees: []
body:

  - type: markdown
    attributes:
      value: |
        
        - Please be aware that some devices are not compatible. Snapdragon chipsets tend to be more compatible than most.
        (Examples: Exynos, Tensor, or other chipsets with a Mali GPU). 
        
        - Games with DRM are currently unsupported and the issue may be closed. 

        - If the bug was due to a hard crash, please attatch logs if possible.

        - If a game shows a soft error about `Failed to initialize graphics...` or anything inside the emulation environment, try editing the container settings.
          Note: Forums and subreddits will provide great help to configure certain games.
        
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      placeholder: Describe what the bug is.
    validations:
      required: true

  - type: textarea
    id: what-actually-happened
    attributes:
      label: Steps to reproduce
      placeholder: What are some steps to reliably reproduce the bug?
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: input
    id: pluvia-version
    attributes:
      label: Pluvia Version
      description: "What version of Pluvia are you using? (ie: 1.3.0)"
    validations:
      required: true

  - type: input
    id: device-model
    attributes:
      label: Device Model
      description: "What device did this happen with? (ie: Retroid Pocket 5)"
    validations:
      required: true

  - type: input
    id: device-android-version
    attributes:
      label: Android Version
      description: "What android version did this occur on? (ie: Android 15)"
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: "Is there any additional info to be added? (ie: logs)"
    validations:
      required: false
  - type: checkboxes
    id: issue-already-searched
    attributes:
      label: New Issue
      description: Is the issue not already posted as an [Issue](https://github.com/oxters168/Pluvia/issues?q=is%3Aissue%20state%3Aopen%20label%3Abug) or in the [Project Board](https://github.com/users/oxters168/projects/1)
      options:
        - label: I have searched and did not find a similar issue to mine already listed.
          required: true
